src/Entity/Movie.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MovieRepository")
 */
class Movie
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=200)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=60)
     */
    private $genre;

    /**
     * @ORM\Column(type="integer")
     */
    private $viewer_age;

    /**
     * @ORM\Column(type="datetime")
     */
    private $premiere;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $director;

    /**
     * @ORM\Column(type="binary", nullable=true)
     */
    private $picture;

    /**
     * @ORM\Column(type="smallint")
     */
    private $duration;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $country;

    /**
     * @ORM\Column(type="string", length=500, nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="float")
     */
    private $price_day;

    /**
     * @ORM\Column(type="float")
     */
    private $price_seanse;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Loan", mappedBy="movie", orphanRemoval=true)
     */
    private $loans;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $sale_price_day;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $sale_price_seanse;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Favorite", mappedBy="movie", orphanRemoval=true)
     */
    private $favorites;

    public function __construct()
    {
        $this->loans = new ArrayCollection();
        $this->favorites = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getGenre(): ?string
    {
        return $this->genre;
    }

    public function setGenre(string $genre): self
    {
        $this->genre = $genre;

        return $this;
    }

    public function getViewerAge(): ?int
    {
        return $this->viewer_age;
    }

    public function setViewerAge(int $viewer_age): self
    {
        $this->viewer_age = $viewer_age;

        return $this;
    }

    public function getPremiere(): ?\DateTimeInterface
    {
        return $this->premiere;
    }

    public function setPremiere(\DateTimeInterface $premiere): self
    {
        $this->premiere = $premiere;

        return $this;
    }

    public function getDirector(): ?string
    {
        return $this->director;
    }

    public function setDirector(string $director): self
    {
        $this->director = $director;

        return $this;
    }

    public function getPicture()
    {
        return $this->picture;
    }

    public function setPicture($picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getDuration(): ?int
    {
        return $this->duration;
    }

    public function setDuration(int $duration): self
    {
        $this->duration = $duration;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(?string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPriceDay(): ?float
    {
        return $this->price_day;
    }

    public function setPriceDay(float $price_day): self
    {
        $this->price_day = $price_day;

        return $this;
    }

    public function getPriceSeanse(): ?float
    {
        return $this->price_seanse;
    }

    public function setPriceSeanse(float $price_seanse): self
    {
        $this->price_seanse = $price_seanse;

        return $this;
    }

    /**
     * @return Collection|Loan[]
     */
    public function getLoans(): Collection
    {
        return $this->loans;
    }

    public function addLoan(Loan $loan): self
    {
        if (!$this->loans->contains($loan)) {
            $this->loans[] = $loan;
            $loan->setMovie($this);
        }

        return $this;
    }

    public function removeLoan(Loan $loan): self
    {
        if ($this->loans->contains($loan)) {
            $this->loans->removeElement($loan);
            // set the owning side to null (unless already changed)
            if ($loan->getMovie() === $this) {
                $loan->setMovie(null);
            }
        }

        return $this;
    }

    public function getSalePriceDay(): ?float
    {
        return $this->sale_price_day;
    }

    public function setSalePriceDay(?float $sale_price_day): self
    {
        $this->sale_price_day = $sale_price_day;

        return $this;
    }

    public function getSalePriceSeanse(): ?float
    {
        return $this->sale_price_seanse;
    }

    public function setSalePriceSeanse(?float $sale_price_seanse): self
    {
        $this->sale_price_seanse = $sale_price_seanse;

        return $this;
    }

    /**
     * @return Collection|Favorite[]
     */
    public function getFavorites(): Collection
    {
        return $this->favorites;
    }

    public function addFavorite(Favorite $favorite): self
    {
        if (!$this->favorites->contains($favorite)) {
            $this->favorites[] = $favorite;
            $favorite->setMovie($this);
        }

        return $this;
    }

    public function removeFavorite(Favorite $favorite): self
    {
        if ($this->favorites->contains($favorite)) {
            $this->favorites->removeElement($favorite);
            // set the owning side to null (unless already changed)
            if ($favorite->getMovie() === $this) {
                $favorite->setMovie(null);
            }
        }

        return $this;
    }
}

src/Controller/MovieController.php
<?php

namespace App\Controller;

use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use App\Entity\Movie;

class MovieController extends AbstractController
{
    public function list()
    {
        $repository = $this->getDoctrine()->getRepository(Movie::class);

        $movies = $repository->findAll();
        
        return $this->render('Movie/list.html.twig', ['movies' => $movies]);
    }

    public function show($id)
    {
        $movie = $this->getDoctrine()
        ->getRepository(Movie::class)
        ->find($id);

        return $this->render('Movie/show.html.twig', ['movie' => $movie]);
    }

    public function previews()
    {
        $repository = $this->getDoctrine()->getRepository(Movie::class);
        
        $movies = $repository->findByDateAfterNow();

        return $this->render('Movie/previews.html.twig', ['movies' => $movies]);
    }

    public function release()
    {
        $repository = $this->getDoctrine()->getRepository(Movie::class);
        
        $movies = $repository->findByRelease();

        return $this->render('Movie/release.html.twig', ['movies' => $movies]);
    }
}

templates/Movie/list.html.twig
{% extends 'base.html.twig' %}
{% block stylesheets%}
  {{ encore_entry_link_tags('app') }}
{% endblock %}
  
{% block body %}
<table class="table">
{% for movie in movies %}
    <tr>
      <td class="border-1"><a href="/movie/{{movie.id}}">title: {{movie.title}}</a></td>
      <td>premiere: {{movie.premiere.date}}</td>
    </tr>
    </a>
    {% endfor %}
</table>
    {# {% for movie in movies %}
     {{movie.title}}
    {% endfor %} #}
{% endblock %}

templates/Movie/previews.html.twig
{% extends 'base.html.twig' %}
{% block stylesheets%}
  {{ encore_entry_link_tags('app') }}
{% endblock %}
  
{% block body %}
<table class="table">
{% for movie in movies %}
    <tr>
      <td class="border-1"><a href="/movie/{{movie.id}}">title: {{movie.title}}</a></td>
      <td>premiere: {{movie.premiere.date}}</td>
    </tr>
    </a>
    {% endfor %}
</table>
    {# {% for movie in movies %}
     {{movie.title}}
    {% endfor %} #}
{% endblock %}

templates/Movie/release.html.twig
{% extends 'base.html.twig' %}
{% block stylesheets%}
  {{ encore_entry_link_tags('app') }}
{% endblock %}
  
{% block body %}
<table class="table">
{% for movie in movies %}
    <tr>
      <td class="border-1"><a href="/movie/{{movie.id}}">title: {{movie.title}}</a></td>
      <td>premiere: {{movie.premiere.date}}</td>
    </tr>
    </a>
    {% endfor %}
</table>
    {# {% for movie in movies %}
     {{movie.title}}
    {% endfor %} #}
{% endblock %}

templates/Movie/show.html.twig
{% extends 'base.html.twig' %}
{% block stylesheets%}
  {{ encore_entry_link_tags('app') }}
{% endblock %}
  
{% block body %}

  <table class="table">
    <tr>
      <td>title: {{movie.title}}</td>
      <td>genre: {{movie.genre}}</td>
      <td>age: {{movie.viewerAge}}</td>
    </tr>
    <tr>
      <td>director: {{movie.director}}</td>
      <td>premiere: {{movie.premiere.date}}</td>
      <td>duration: {{movie.duration}}</td>
    </tr>
    <tr>
      <td>description:     {{movie.description}}</td>

      {% if not movie.salePriceDay %}
        <td>price day: {{movie.priceDay}}</td>
      {% else %}
         <td>price on day from {{movie.priceDay}} on {{movie.salePriceDay}} </td>
      {% endif %}

      {% if not movie.salePriceSeanse %}
      <td>price seanse: {{movie.priceSeanse}}</td>
      {% else %}
      <td>price on seanse from {{movie.priceSeanse}} on {{movie.salePriceSeanse}} </td>
      {% endif %}
    </tr>
    <tr>
      <td><button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
        Buy
      </button>
      </td>
      <td><input id="toggle-heart" type="checkbox" />
          <label for="toggle-heart">❤</label>
      </td>
    </tr>
</table>

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
       <form action="/loan/create" method="post">
          Sale Day: <input type="text" id="price_day" name="day"><br>
          Sale Seanse:  <input type="text" id="price_seanse" name="seanse"><br>
           <input type="hidden"  name="movie_id" value="{{movie.id}}">
           <input type="hidden"  name="user_id" value="{{app.user.id}}">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Buy</button>
      </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}

{% block javascripts %}
  {{ encore_entry_script_tags('app') }}
   <script src="{{ asset('js/buy.js') }}"></script>
{% endblock %}